### ISSUE TITLE
【bug】签到报错，新的错误码，-50001

### ISSUE THREAD

**Issue by mengluo04** [ZZZure/ZZZeroUID#11]
签到失败
![image](https://github.com/user-attachments/assets/660d3772-f35d-4309-81fe-f9b52743aa6b)
但是消息推送显示的成功
![image](https://github.com/user-attachments/assets/5dc42340-c10f-47eb-af92-4efd7388f600)

**Comment by KimigaiiWuyi** [comment]
请使用`core全部更新`之后检查是否正常, 昨晚已修复

**Comment by mengluo04** [comment]
> 请使用`core全部更新`之后检查是否正常, 昨晚已修复

早上看到commit更新了试了下好像对了，今晚再看看结果，这是又换签到接口了？

**Comment by KimigaiiWuyi** [comment]
> > 请使用`core全部更新`之后检查是否正常, 昨晚已修复
> 
> 早上看到commit更新了试了下好像对了，今晚再看看结果，这是又换签到接口了？

确实, 我昨晚注意到了, 修完了测试应该是正常的

**Comment by mengluo04** [comment]
> > > 请使用`core全部更新`之后检查是否正常, 昨晚已修复
> > 
> > 
> > 早上看到commit更新了试了下好像对了，今晚再看看结果，这是又换签到接口了？
> 
> 确实, 我昨晚注意到了, 修完了测试应该是正常的

好咧，辛苦了
