### ISSUE TITLE
请问你们的抽卡记录管理专用的翻译数据库是怎么搓出来的？

### ISSUE THREAD

**Issue by ShikiSuen** [ZZZure/ZZZeroUID#14]
Dimbreath 的 ZenlessData 在 GitHub 和 GitLab 都被搞掉了。
抽卡记录总得需要一个翻译数据库来以多语言显示抽卡内容吧？
就好奇你们是怎么实作的。

**Comment by KimigaiiWuyi** [comment]
https://git.mero.moe/dimbreath/ZenlessData
