### ISSUE TITLE
几天前还能正常加载使用这几天突然不能加载，更新了也还是不行

### ISSUE THREAD

**Issue by dwsxx1** [ZZZure/ZZZeroUID#19]
![8895A1EC5E468028EE7CAF8082ABFA2D](https://github.com/user-attachments/assets/b8a43de5-3b26-4bdb-8820-7193553d58c9)

**Comment by KimigaiiWuyi** [comment]
请截图一下完整的报错堆栈，下面应该还有很多信息的
或者优先尝试`core全部更新`之后再看看能否加载

**Comment by KimigaiiWuyi** [comment]
更新后应该已修复 https://github.com/ZZZure/ZZZeroUID/pull/20

**Comment by dwsxx1** [comment]
谢谢大佬
