### ISSUE TITLE
更新最新版本出现报错

### ISSUE THREAD

**Issue by ocetars** [ZZZure/ZZZeroUID#3]
> ImportError: cannot import name 'GS_BASE' from 'plugins.StarRailUID.StarRailUID.sruid_utils.api.mys.api' (/home/uavpub/bot/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/sruid_utils/api/mys/api.py)
  File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 121, in load_plugins
    self.load_dir_plugins(path, True)
  File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 172, in load_dir_plugins
    importlib.import_module(f'{_p}')
  File "/home/uavpub/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/__init__.py", line 9, in <module>
    from .draw_role_info import draw_role_img
  File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/draw_role_info.py", line 9, in <module>
    from ..utils.zzzero_api import zzz_api
  File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/zzzero_api.py", line 1, in <module>
    from .api.request import ZZZApi
  File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/request.py", line 18, in <module>
    from .api import (
  File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/api.py", line 1, in <module>
    from gsuid_core.utils.api.mys.api import GS_BASE, GS_BASE_OS, RECORD_BASE
07-14 16:46:53 [WARNING] gsuid_core.server | 插件ZZZeroUID加载失败

**Comment by ocetars** [comment]
**完整报错**

> 07-14 16:46:51 [INFO] gsuid_core.server | [GsCore] 开始加载插件... 
> 07-14 16:46:52 [INFO] plugins.StarRailUID.StarRailUID.starrailuid_resource | [sr资源文件下载] 正在检查与下载缺失的资源文件,可能需要较长时间,请稍等 
> 07-14 16:46:52 [INFO] gsuid_core.utils.download_resource.download_core | [GsCore资源下载]测速中... 
> 07-14 16:46:52 [INFO] gsuid_core.server | [BAI] 检测是否存在失效仓库... 
> 07-14 16:46:52 [SUCCESS] gsuid_core.server | 插件StarRailUID导入成功! 
> 07-14 16:46:52 [SUCCESS] gsuid_core.server | 插件gs_test导入成功! 
> 07-14 16:46:53 [SUCCESS] gsuid_core.server | 插件core_command导入成功! 
> 2024-07-14 16:46:53.076 | ERROR    | gsuid_core.server:load_plugins:149 - 加载插件时发生错误: cannot import name 'GS_BASE' from 'plugins.StarRailUID.StarRailUID.sruid_utils.api.mys.api' (/home/uavpub/bot/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/sruid_utils/api/mys/api.py)
> Traceback (most recent call last):
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/core.py", line 15, in <module>
>     from gsuid_core.gss import gss  # noqa: E402
> 
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/gss.py", line 12, in <module>
>     gss.load_plugins()
>     │   └ <function GsServer.load_plugins at 0x7fb88c68ff60>
>     └ <gsuid_core.server.GsServer object at 0x7fb88dd63310>
> 
> > File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 121, in load_plugins
>     self.load_dir_plugins(path, True)
>     │    │                └ PosixPath('/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID')
>     │    └ <function GsServer.load_dir_plugins at 0x7fb88c698040>
>     └ <gsuid_core.server.GsServer object at 0x7fb88dd63310>
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 172, in load_dir_plugins
>     importlib.import_module(f'{_p}')
>     │         └ <function import_module at 0x7fb88f655580>
>     └ <module 'importlib' from '/home/uavpub/anaconda3/lib/python3.11/importlib/__init__.py'>
> 
>   File "/home/uavpub/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            │          │           │    │        │        └ 0
>            │          │           │    │        └ None
>            │          │           │    └ 0
>            │          │           └ 'plugins.ZZZeroUID.ZZZeroUID.zzzerouid_roleinfo'
>            │          └ <function _gcd_import at 0x7fb890083d80>
>            └ <module '_frozen_importlib' (frozen)>
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/__init__.py", line 9, in <module>
>     from .draw_role_info import draw_role_img
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/draw_role_info.py", line 9, in <module>
>     from ..utils.zzzero_api import zzz_api
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/zzzero_api.py", line 1, in <module>
>     from .api.request import ZZZApi
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/request.py", line 18, in <module>
>     from .api import (
> 
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/api.py", line 1, in <module>
>     from gsuid_core.utils.api.mys.api import GS_BASE, GS_BASE_OS, RECORD_BASE
> 
> ImportError: cannot import name 'GS_BASE' from 'plugins.StarRailUID.StarRailUID.sruid_utils.api.mys.api' (/home/uavpub/bot/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/sruid_utils/api/mys/api.py)
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 121, in load_plugins
>     self.load_dir_plugins(path, True)
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/server.py", line 172, in load_dir_plugins
>     importlib.import_module(f'{_p}')
>   File "/home/uavpub/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/__init__.py", line 9, in <module>
>     from .draw_role_info import draw_role_img
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/zzzerouid_roleinfo/draw_role_info.py", line 9, in <module>
>     from ..utils.zzzero_api import zzz_api
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/zzzero_api.py", line 1, in <module>
>     from .api.request import ZZZApi
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/request.py", line 18, in <module>
>     from .api import (
>   File "/home/uavpub/bot/gsuid_core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID/utils/api/api.py", line 1, in <module>
>     from gsuid_core.utils.api.mys.api import GS_BASE, GS_BASE_OS, RECORD_BASE
> 07-14 16:46:53 [WARNING] gsuid_core.server | 插件ZZZeroUID加载失败

**Comment by KimigaiiWuyi** [comment]
请使用 core全部更新 命令 更新core+全部插件
你这个情况是core没到最新

**Comment by ocetars** [comment]
> 请使用 core全部更新 命令 更新core+全部插件 你这个情况是core没到最新

已解决，感谢
