### ISSUE TITLE
错误代码-999

### ISSUE THREAD

**Issue by ocetars** [ZZZure/ZZZeroUID#4]
群内一个群友出现的问题，其他人使用正常。尝试了删除绑定和CK，重新扫码登录，依然无法解决。log没有出现报错
![Screenshot_2024-07-22-11-56-24-314_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/5662e992-533d-42b6-96eb-4ed8dce2f8f3)

![Image_1721620738409.png](https://github.com/user-attachments/assets/dba89614-d1ee-449b-b0fa-e45ca748408a)

**Comment by ocetars** [comment]
此可以正常使用抽卡记录相关功能，但是涉及到查询米游社的功能都会出现该错误

**Comment by KimigaiiWuyi** [comment]
可以尝试`core全部更新`同时更新core+zzzuid之后, `gs重启`重启后,再次尝试设备登陆,之后再试试

**Comment by ocetars** [comment]
已解决
