### ISSUE TITLE
zzz刷新面板无反应

### ISSUE THREAD

**Issue by mengluo04** [ZZZure/ZZZeroUID#6]
`zzz查询爱莲`返回[绝区零] 未找到该角色信息, 请先使用[zzz刷新面板]进行刷新!
`zzz刷新面板`无响应，日志无输出，已经是debug模式

**Comment by KimigaiiWuyi** [comment]
请贴出日志截图

**Comment by mengluo04** [comment]
> 请贴出日志截图

![image](https://github.com/user-attachments/assets/981ba622-b49d-4944-bf7d-c2ddb17362ee)
![image](https://github.com/user-attachments/assets/ed25d021-e465-4fb9-b09c-6ccdda00f1a1)
日志只有查询的记录

**Comment by KimigaiiWuyi** [comment]
> > 请贴出日志截图
> 
> ![image](https://private-user-images.githubusercontent.com/32565940/355752107-981ba622-b49d-4944-bf7d-c2ddb17362ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjIyMjIsIm5iZiI6MTcyMzAyMTkyMiwicGF0aCI6Ii8zMjU2NTk0MC8zNTU3NTIxMDctOTgxYmE2MjItYjQ5ZC00OTQ0LWJmN2QtYzJkZGIxNzM2MmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA5MTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNzc0MmNmYTYyZGFjODNiYjgxZGRiMjNiZjlhM2VhMTk2YTdkMTlmMWJjYjU3N2EyY2UxNTVkYjQwNWM5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3iE3qMtGLnXWfJHvzDpiG3FRv53U4Fc9QWlnx6ivUU) ![image](https://private-user-images.githubusercontent.com/32565940/355752147-ed25d021-e465-4fb9-b09c-6ccdda00f1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjIyMjIsIm5iZiI6MTcyMzAyMTkyMiwicGF0aCI6Ii8zMjU2NTk0MC8zNTU3NTIxNDctZWQyNWQwMjEtZTQ2NS00ZmI5LWIwOWMtNmNjZGRhMDBmMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA5MTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjQyMDdkMmM3MGVjOTM0MTMwOTI1NDAxNjdiYzhkMjRhMjA4YjcxOTFhMzNjYWFhOTFjZWE2MjMxNmFkZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POgvnTkI5jWyn9q-gv8-Os0-z_69LZA0ppgEyx4_Ol0) 日志只有查询的记录

日志没有开启DEBUG,请于`config.json`中修改后重启再触发命令后截图
```
"log": {
    "level": "DEBUG" // 日志等级，一般为`INFO`且无需修改, 开发者和反馈Bug的时候开到`DEBUG`
  },
```

**Comment by Jerry-FaGe** [comment]
https://github.com/KimigaiiWuyi/GenshinUID/issues/635
